import {METRICS,SUPPLEMENTS,LEVELS,hasValue,today,addDays,validDate,formatDate,metricValue,metricPoints,weekStats,weekPlan,mode,familyPeriod,visibleFields} from './core.mjs';
import {esc,icon,field,sessionRows,renderActivity,weeklyChart} from './ui.mjs';
import {exerciseHtml} from './exercises.mjs';
import {metricSummary,trendChart,pressureChart} from './insights.mjs';
export const MODES=[['normal','Běžný týden'],['calm','Klidný týden'],['busy','Nabitý týden'],['family','Rodinný režim']];
export function modeControls(s){const current=mode(s);return `<div class="segmented week-modes" aria-label="Režim týdne">${MODES.map(([key,label])=>`<button data-action="mode" data-mode="${key}" aria-pressed="${current===key}" ${familyPeriod(s.profile)&&key!=='family'?'disabled':''}>${label}</button>`).join('')}</div>`;}
const heading=(id,title,body)=>`<div class="page-heading"><div><span class="eyebrow">PROSTOR PRO POHYB</span><h1 id="${id}Heading">${title}</h1><p>${body}</p></div></div>`;
export function renderWeek(s){
 const stats=weekStats(s),rows=sessionRows(s),required=rows.filter(x=>!x.optional),done=required.filter(x=>x.logged).length,minutes=required.reduce((n,x)=>n+x.duration,0),m=mode(s),extras=stats.rows.filter(w=>!rows.some(x=>x.logged?.id===w.id));
 return heading('today','Tvůj týden',`${formatDate(stats.start)} – ${formatDate(stats.end,true)} · Rozlož si pohyb podle svého času.`)+`
 <article class="card week-overview"><div class="week-overview-head"><div><span class="eyebrow">SPLNĚNÍ PLÁNU</span><h2>${done} z ${required.length} základních jednotek</h2></div><span class="pill">${stats.minutes} min pohybu</span></div><progress class="plan-progress" value="${done}" max="${required.length}" aria-label="Splněné základní jednotky"></progress>
 ${modeControls(s)}<p class="mode-description">${m==='calm'?'Máš víc prostoru: základ zůstává, navíc můžeš přidat lehký pohyb. Intenzita se nezvyšuje.':m==='busy'?'Dvě krátké jednotky, které se vejdou i do pracovně náročného týdne.':m==='family'?'Krátký pohyb podle spánku a energie. Rodina má přednost.':'Základ na tento týden: '+minutes+' minut. Další pohyb je dobrovolný.'}${familyPeriod(s.profile)?' Rodinné období je zapnuté automaticky podle data v Nastavení.':''}</p></article>
 <div class="weekly-sessions">${rows.map((item,i)=>`<article class="card workout-card ${item.logged?'completed':''}"><div class="workout-card-head"><span class="slot-number">${item.logged?'✓':String(i+1).padStart(2,'0')}</span><div><div class="workout-kicker">${item.optional?'VOLITELNĚ NAVÍC':'ZÁKLAD TÝDNE'} · ${item.duration} MIN</div><h2>${esc(item.title)}</h2></div><button class="button ${item.logged?'subtle':'primary'}" data-action="session" data-id="${item.id}">${item.logged?'Upravit záznam':'Zapsat splnění'}</button></div>${item.logged?`<p class="workout-done">Splněno ${formatDate(item.logged.date)} · ${item.logged.duration} min</p>`:''}<details class="workout-detail"><summary>${item.exercise?'Cviky, videa a postup':'Jak na to'}</summary><p>${esc(item.details)}</p>${item.exercise?`<button class="text-button" data-action="video" data-video="warmup">▷ Video rozcvičky</button>${exerciseHtml(item.exercise)}`:''}</details></article>`).join('')}</div>
 ${extras.length?`<details class="card extra-activity"><summary>Další pohyb tento týden · ${extras.length} záznamů</summary>${extras.map(w=>`<div class="extra-row"><span>${formatDate(w.date)} · ${esc(w.type)} · ${w.duration} min</span><button class="text-button" data-action="edit-workout" data-id="${esc(w.id)}">Upravit</button></div>`).join('')}</details>`:''}
 <div class="week-footer"><span>Úroveň ${s.profile.planLevel+1}/4 · ${LEVELS[s.profile.planLevel].name}</span><button class="text-button" data-page="plan">Náročnost a další postup →</button></div><div class="week-links"><button class="button" data-action="log">＋ Další pohyb</button><button class="text-button" data-page="progress">Celkový pokrok →</button><button class="text-button settings-mobile" data-page="settings">Nastavení →</button></div>`;
}
function lastReading(s,group){if(group.id==='pressure'){const rows=s.measurements.filter(m=>group.keys.every(k=>hasValue(m[k]))).sort((a,b)=>a.date.localeCompare(b.date)),last=rows.at(-1);return last?`Poslední: ${group.keys.map(k=>last[k]).join('/')} mmHg · ${formatDate(last.date,true)}`:'Zatím bez záznamu';}const last=metricPoints(s,group.keys[0]).at(-1);return last?'Poslední: '+esc(metricValue(group.keys[0],last.value))+' · '+formatDate(last.date,true):'Zatím bez záznamu';}
export function selectField(name,label,value,options){return `<label class="field"><span>${label}</span><select name="${name}" required><option value="">Vyber…</option>${options.map(([v,l])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${l}</option>`).join('')}</select></label>`;}
export function measurementGroups(s){const keys=visibleFields(s).metrics,definitions=[{id:'sleep',title:'Spánek',keys:['sleepMinutes'],hint:'Kolik jsi naspal za noc.'},{id:'weight',title:'Hmotnost',keys:['weight'],hint:'Jedna hodnota v kilogramech.'},{id:'pressure',title:'Krevní tlak',keys:['systolicBp','diastolicBp'],hint:'Horní a dolní hodnota z tlakoměru.'},{id:'pulse',title:'Klidový tep',keys:['restingHr'],hint:'Počet tepů za minutu v klidu.'},{id:'energy',title:'Energie',keys:['energy'],hint:'Jak se dnes cítíš.'}];return definitions.map(g=>({...g,keys:g.keys.filter(k=>keys.includes(k))})).filter(g=>g.keys.length);}
export function measurementInputs(s,group,date){const record=s.measurements.find(m=>m.date===date)||{};return group.keys.map(k=>{if(k==='sleepMinutes'){const minutes=record[k];return selectField('sleepHours','Hodiny',hasValue(minutes)?Math.floor(minutes/60):'',Array.from({length:24},(_,i)=>[i,i+' h']))+selectField('sleepMins','Minuty',hasValue(minutes)?minutes%60:'',Array.from({length:60},(_,i)=>[i,String(i).padStart(2,'0')+' min']));}if(k==='energy')return selectField(k,'Energie',record[k]??'',[['1','1 · Vyčerpaný'],['2','2 · Unavený'],['3','3 · Tak akorát'],['4','4 · Dobrý den'],['5','5 · Plný energie']]);const spec=METRICS[k];return field(k,(k==='systolicBp'?'Horní (systolický)':k==='diastolicBp'?'Dolní (diastolický)':spec.label)+' · '+spec.unit,record[k]??'',{type:'number',min:spec.min,max:spec.max,step:spec.step,required:true});}).join('');}
export function renderMeasurements(s,context={}){const date=validDate(context.measureDate)?context.measureDate:today(),groups=measurementGroups(s),record=s.measurements.find(m=>m.date===date)||{},routine=visibleFields(s).supplements;
 return heading('measurements','Zapsat měření','Vyber jen to, co chceš dnes zapsat. Každá karta se ukládá samostatně.')+`
 <div class="measurement-toolbar"><label class="field"><span>Den měření</span><input id="measurementDate" type="date" value="${date}" max="${today()}" required></label><button class="button subtle" data-action="measure-today">Dnes</button><button class="text-button" data-page="progress">Grafy a průměry →</button></div>
 <div class="measurement-entry-grid">${groups.map(group=>{const saved=group.keys.every(k=>hasValue(record[k])),last=metricPoints(s,group.keys[0]).at(-1);return `<article class="card entry-card" id="measure-${group.id}"><div class="card-head"><h2>${group.title}</h2><span class="entry-status ${saved?'saved':''}">${saved?'✓ Uloženo':'Nevyplněno'}</span></div><p class="entry-hint">${group.hint}</p><form data-measure-group="${group.id}"><input type="hidden" name="date" value="${date}"><div class="entry-inputs ${group.keys.length>1||group.id==='sleep'?'paired':''}">${measurementInputs(s,group,date)}</div><button class="button primary" type="submit">${saved?'Uložit změny':'Uložit '+(group.id==='sleep'?'spánek':group.id==='weight'?'hmotnost':group.id==='pressure'?'tlak':group.id==='pulse'?'tep':'energii')}</button><span class="entry-save-result" role="status"></span></form><p class="last-reading">${lastReading(s,group)}</p></article>`;}).join('')}</div>
 ${!groups.length?'<div class="card">Pro tento účet zatím nejsou vybraná pravidelná měření.</div>':''}
 ${routine.length?`<article class="card subsection"><details><summary>Denní rutina · ${formatDate(date)}</summary><div class="supplement-grid">${routine.map(k=>`<label class="supplement-chip"><input type="checkbox" data-supplement="${k}" data-date="${date}" ${s.supplements[date]?.[k]?'checked':''}>${SUPPLEMENTS[k]}</label>`).join('')}</div><p class="sources">Evidence rutiny, bez doporučení dávkování.</p></details></article>`:''}<button class="text-button settings-mobile" data-page="settings">Nastavení a účet →</button>`;
}
function averages(s,key){const data=metricSummary(s,key);return `<div class="average-grid"><div><small>Posledních 7 dní</small><strong>${data.recentAverage===null?'Bez měření':esc(metricValue(key,data.recentAverage))}</strong><span>${data.recent.length} měření</span></div><div><small>Dlouhodobý průměr</small><strong>${data.average===null?'Bez měření':esc(metricValue(key,data.average))}</strong><span>${data.all.length} měření · celá historie</span></div></div>`;}
export function renderInsights(s,context={}){const prefs=context.charts||{range:'all',average:true,trend:true,references:true},tracking=visibleFields(s),metrics=tracking.metrics.filter(k=>!['systolicBp','diastolicBp'].includes(k)),pressure=tracking.metrics.some(k=>['systolicBp','diastolicBp'].includes(k)),rows=[...s.measurements].filter(m=>tracking.metrics.some(k=>hasValue(m[k]))).sort((a,b)=>b.date.localeCompare(a.date));
 return heading('progress','Pokrok v souvislostech','Měření, průměry a plnění plánu na jednom místě.')+`
 <article class="card"><div class="card-head"><h2>Pohyb v čase</h2><small>Posledních 8 týdnů</small></div>${weeklyChart(s)}<details class="activity-archive"><summary>Historie pohybu a úprava záznamů</summary>${renderActivity(s)}</details></article>
 <div class="chart-toolbar"><label class="field"><span>Období v grafech</span><select id="chartRange">${[['30','30 dní'],['90','90 dní'],['all','Celá historie']].map(([v,l])=>`<option value="${v}" ${prefs.range===v?'selected':''}>${l}</option>`).join('')}</select></label><label><input type="checkbox" data-chart-option="average" ${prefs.average?'checked':''}> Dlouhodobý průměr</label><label><input type="checkbox" data-chart-option="trend" ${prefs.trend?'checked':''}> Klouzavý průměr</label><label><input type="checkbox" data-chart-option="references" ${prefs.references?'checked':''}> Hranice tlaku</label></div>
 <div class="measurement-cards">${metrics.map(key=>{const last=metricSummary(s,key).last;return `<article class="card measurement-card"><div class="card-head"><h2>${METRICS[key].label}</h2><button class="text-button" data-action="measure" data-metric="${key}">Zapsat ＋</button></div><div class="number">${last?esc(metricValue(key,last.value)):'—'}</div><div class="reading-date">${last?'Poslední měření '+formatDate(last.date,true):'Zatím bez měření'}</div>${averages(s,key)}${trendChart(s,key,prefs.range,prefs.average,prefs.trend)}</article>`;}).join('')}
 ${pressure?`<article class="card measurement-card pressure-card"><div class="card-head"><h2>Krevní tlak</h2><button class="text-button" data-action="measure" data-metric="systolicBp">Zapsat ＋</button></div><p class="section-description">Systolický a diastolický tlak · mmHg</p>${pressureChart(s,prefs.range,prefs.references)}<div class="pressure-averages">${['systolicBp','diastolicBp'].filter(k=>tracking.metrics.includes(k)).map(k=>`<div><h3>${METRICS[k].label}</h3>${averages(s,k)}</div>`).join('')}</div><details class="reference-note"><summary>Co znamenají referenční čáry?</summary><p>Pro domácí měření je orientační hranicí vysokého tlaku 135 systolicky nebo 85 diastolicky. V ordinaci se používá 140/90. Nízký tlak se běžně označuje jako méně než 90/60 mmHg. Čáry nejsou osobním léčebným cílem a jediný záznam neurčuje diagnózu; opakovaně zvýšené hodnoty prober s lékařem.</p><p><a href="https://www.nhs.uk/conditions/high-blood-pressure/" target="_blank" rel="noopener">NHS: vysoký tlak</a> · <a href="https://www.nhs.uk/conditions/low-blood-pressure-hypotension/" target="_blank" rel="noopener">NHS: nízký tlak</a></p></details></article>`:''}</div>
 <p class="sources">Průměr za 7 dní počítá jen vyplněné hodnoty od ${formatDate(addDays(today(),-6))} do dneška. Prázdné dny se nepočítají jako nula. Dlouhodobý průměr používá celou historii bez ohledu na zvolený výřez grafu. Klouzavý průměr používá posledních až 5 měření.</p>
 ${rows.length?`<article class="card subsection"><details><summary>Historie měření · ${rows.length} dní</summary><div class="table-wrap"><table><thead><tr><th>Datum</th>${tracking.metrics.map(k=>`<th>${METRICS[k].label}</th>`).join('')}<th></th></tr></thead><tbody>${rows.map(m=>`<tr><td>${formatDate(m.date,true)}</td>${tracking.metrics.map(k=>`<td>${esc(metricValue(k,m[k]))}</td>`).join('')}<td><button class="text-button" data-action="measure" data-date="${m.date}">Upravit</button></td></tr>`).join('')}</tbody></table></div></details></article>`:''}`;
}
