import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,weekPlan,trainingStatus,addDays,visibleFields,mergeChanges,TRAINING_STAGES} from '../core.mjs';
const fixture=(profile={})=>normalize({version:4,profile:{restartDate:'2026-10-05',milestoneEnabled:false,raceEnabled:false,...profile}});
function logWeek(s,week,all=true){const plan=weekPlan(s,week);plan.filter(p=>all||!p.optional).forEach((p,i)=>s.customWorkouts.push({id:week+'-'+i,planSessionId:p.id,date:addDays(week,i*2),duration:p.duration,type:p.type,training:p.training,feeling:4,pain:0}));}
test('vitamins are individually visible even with frozen old tracking; unrelated checkboxes survive sync',()=>{const s=fixture({tracking:{metrics:[],workoutFields:[],supplements:['magnesium']}});assert.deepEqual(visibleFields(s).supplements,['magnesium','vitaminD','vitaminB','vitaminC']);s.supplements['2026-10-05']={magnesium:true,vitaminD:true};const other=structuredClone(s);other.supplements['2026-10-05'].vitaminC=true;const merged=mergeChanges(other,s,{supplements:{'2026-10-05':['vitaminD']}});assert.equal(merged.supplements['2026-10-05'].vitaminC,true);assert.equal(merged.supplements['2026-10-05'].magnesium,true);});
test('two completed weeks advance one step, current week entries cannot increase its target',()=>{const s=fixture();logWeek(s,'2026-10-05');assert.equal(trainingStatus(s,'2026-10-11').stage,0);assert.equal(trainingStatus(s,'2026-10-12').stage,0);logWeek(s,'2026-10-12');assert.equal(trainingStatus(s,'2026-10-19').stage,1);const before=weekPlan(s,'2026-10-19').map(x=>x.duration);logWeek(s,'2026-10-19');assert.deepEqual(weekPlan(s,'2026-10-25').map(x=>x.duration),before);assert.equal(trainingStatus(s,'2026-10-26').phase,'deload');});
test('empty calendar does not increase load; two inactive weeks reset it',()=>{const s=fixture({trainingStage:7});assert.equal(trainingStatus(s,'2026-10-12').stage,7);assert.equal(trainingStatus(s,'2026-10-19').stage,0);assert.equal(trainingStatus(s,'2027-03-01').stage,0);});
test('optional third session must be established before it becomes required',()=>{const s=fixture({trainingStage:3});logWeek(s,'2026-10-05',false);logWeek(s,'2026-10-12',false);assert.ok(trainingStatus(s,'2026-10-19').stage<4);const ready=fixture({trainingStage:3});logWeek(ready,'2026-10-05');logWeek(ready,'2026-10-12');assert.equal(trainingStatus(ready,'2026-10-19').stage,4);});
test('short busy weeks do not qualify for progression and stress blocks it',()=>{const s=fixture({weekMode:'busy'});logWeek(s,'2026-10-05');logWeek(s,'2026-10-12');assert.equal(trainingStatus(s,'2026-10-19').stage,0);const painful=fixture();logWeek(painful,'2026-10-05');logWeek(painful,'2026-10-12');painful.customWorkouts[0].pain=5;assert.equal(trainingStatus(painful,'2026-10-19').stage,0);painful.measurements.push({date:'2026-10-19',energy:1});assert.equal(trainingStatus(painful,'2026-10-19').phase,'hold');assert.ok(weekPlan(painful,'2026-10-19').every(x=>x.optional));});
test('race proximity alone never introduces hard sessions, established athletes get one controlled session',()=>{const s=fixture({trainingStage:8,autoProgress:false,raceEnabled:true,raceDate:'2026-11-15'});assert.equal(trainingStatus(s,'2026-10-05').specific,false);logWeek(s,'2026-10-05');logWeek(s,'2026-10-12');assert.equal(trainingStatus(s,'2026-10-19').specific,true);assert.equal(weekPlan(s,'2026-10-19').filter(x=>x.title.includes('úseky')).length,1);assert.equal(weekPlan(s,'2026-10-19')[0].duration,TRAINING_STAGES[8].minutes[0]);});
test('taper, final rest days and recovery are driven by exact race dates, disabled races have no effect',()=>{const s=fixture({trainingStage:8,autoProgress:false,raceEnabled:true,raceDate:'2026-11-15'});assert.equal(trainingStatus(s,'2026-11-01').factor,.65);assert.equal(trainingStatus(s,'2026-11-08').factor,.45);const early=weekPlan(s,'2026-11-01').reduce((n,x)=>n+x.duration,0),late=weekPlan(s,'2026-11-08').reduce((n,x)=>n+x.duration,0);assert.ok(late<early);assert.ok(weekPlan(s,'2026-11-13').every(x=>x.optional&&x.duration<=10));assert.equal(trainingStatus(s,'2026-11-15').phase,'race');assert.equal(trainingStatus(s,'2026-11-16').phase,'recovery');assert.equal(trainingStatus(s,'2026-11-23').factor,.6);s.profile.raceEnabled=false;assert.equal(trainingStatus(s,'2026-11-08').phase,'build');s.profile.raceEnabled=true;s.profile.raceDate='';assert.equal(trainingStatus(s,'2026-11-08').phase,'build');});
test('family period overrides extra activity and controlled hills, including around a race',()=>{const s=fixture({trainingStage:8,autoProgress:false,weekMode:'calm',familyDate:'2028-05-20',raceEnabled:true,raceDate:'2028-05-10'});const status=trainingStatus(s,'2028-05-01');assert.equal(status.mode,'family');assert.equal(status.specific,false);assert.ok(weekPlan(s,'2028-05-01').reduce((n,x)=>n+x.duration,0)<=25);});
